// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("https://www.toolsqa.com/selenium-certification/?q=Header");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.name("your-name")).click();
    driver.findElement(By.name("your-name")).sendKeys("Ivan");
    driver.findElement(By.name("your-email")).sendKeys("Test");
    driver.findElement(By.name("your-mobile")).click();
    driver.findElement(By.name("your-mobile")).sendKeys("0000000000");
    driver.findElement(By.name("your-country")).click();
    driver.findElement(By.name("your-country")).sendKeys("ukraine");
    driver.findElement(By.name("your-city")).click();
    driver.findElement(By.name("your-city")).sendKeys("Vinnytsya");
    driver.findElement(By.cssSelector("#wpcf7-f24983-p35401-o1 .wpcf7-submit")).click();
    driver.close();
  }
}
